language: python
python:
  - "3.6"
  - "3.7"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install codecov coverage pytest==3.3.2 python_coveralls wisepy lice

script:
  - python setup install
  - coverage run test.py
  - coverage report

after_success:
  - codecov
  - coveralls